version: '3.8'

services:
  # Сервис для MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: backup_password
      MYSQL_DATABASE: test_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Сервис для PostgreSQL
  postgresql:
    image: postgres:14
    container_name: postgresql
    environment:
      POSTGRES_USER: backup_user
      POSTGRES_PASSWORD: backup_password
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  # Сервис для MongoDB
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: backup_user
      MONGO_INITDB_ROOT_PASSWORD: backup_password
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

  # Сервис для вашего приложения
  backup-tool:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backup-tool
    depends_on:
      - mysql
      - postgresql
      - mongodb
    environment:
      - BACKUP_TOOL_LOGGING_FILE=/app/data/logs/app.log
      - BACKUP_TOOL_STORAGE_LOCAL_PATH=/app/data/backups
    volumes:
      - ./pkg/config:/app/config # Монтируем локальную директорию с конфигами
      - ./data/logs:/app/data/logs
      - ./data/backups:/app/data/backups
    command: ["--config", "/app/config/mysql.yaml", "--type", "mysql", "--command", "backup", "--backup-file", "/app/data/backups/mysql/mydb.sql"]

volumes:
  mysql_data:
  postgresql_data:
  mongodb_data: