database:
  type: mongodb
  host: localhost
  port: 27017
  username: backup_user
  password: backup_password
  dbname: test_db
  auth-db: admin

storage:
  local_path: data/backups
  cloud_type: s3
  bucket: my-backup-bucket

logging:
  level: debug       
  file: data/logs/app.log
  format: "text"

notification:
  slack_webhook_url: https://hooks.slack.com/services/...