database:
  type: mysql
  host: localhost
  port: 3306
  username: u-username
  password: u-password
  dbname: u-db-name

storage:
  local_path:  data/backups
  cloud_type: s3
  bucket: my-backup-bucket

logging:
  level: info    
  file: data/logs/app.log
  format: text 

notification:
  slack_webhook_url: https://hooks.slack.com/services/...