database:
  type: postgresql
  host: localhost
  port: 5432
  username: postgres
  password: root
  dbname: postgres

storage:
  local_path: data/backups
  cloud_type: s3
  bucket: my-backup-bucket

logging:
  level: info      
  file: data/logs/app.log
  format: text  

notification:
  slack_webhook_url: https://hooks.slack.com/services/...