database:
  type: mysql
  host: localhost
  port: 3306
  username: root
  password: ito21
  dbname: mydb

storage:
  local_path: /backups
  cloud_type: s3
  bucket: my-backup-bucket

logging:
  level: info       # Уровень логирования (info, warn, error, debug)
  file: "logs/app.log" # Путь к файлу логов
  format: "text"  

notification:
  slack_webhook_url: https://hooks.slack.com/services/...